# Generated by Django 6.0.4 on 2026-04-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fecha_precio', models.DateTimeField()),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.activo')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.moneda')),
            ],
            options={
                'unique_together': {('moneda', 'activo', 'fecha_precio')},
            },
        ),
    ]
